Buttons please
NYPL/design pull request #11
Opened 2016-12-19 22:03 UTC by ricardoom

Gentleman,
for Issue #5 take a look and let me know it if fulfills the request in a way to your liking. Happy to make any improvements you might like see.

2016-12-19 22:34 UTC, ricardoom commented
made a few modifications and fixed some omissions...

2016-12-19 23:08 UTC, mgiraldo requested changes

2016-12-19 23:08 UTC, mgiraldo commented on toolkit/sass/_buttons.scss
> +.squared-button {
let's not impose a specific class. we should rather use a mixin like `rounded-button` that then is used by each application like so:

    .my-custom-class {
        @include rounded-button;
    }

this way each application does their html as they see fit as long as it complies with the guidelines.

also, this could all be part of `simple-button` which would receive an optional `radius` (default is zero for a squared button).

if you want to have “pre-baked” buttons like `request-button` then you could just include `simple-button` with the necessary parameters to produce the request look. for example:

    @mixin request-button {
        @include simple-button(green, white, 0);
    } 

let's also go with dash-cased naming (instead of camelCased) , similar to [what airbnb does](https://github.com/airbnb/css).

2016-12-19 23:08 UTC, mgiraldo commented on toolkit/sass/_grid.scss
> +//@import "css3";
this is my bad. i forgot to add that file to the repo friday. i need to add it.

2016-12-19 23:08 UTC, mgiraldo commented on toolkit/sass/_grid.scss
> +  @warn "missing mixin here...";
see previous comment

2016-12-20 15:45 UTC, EdwinGuzman commented on toolkit/sass/_colors.scss
> +@warn '_colors.scss TODO: employ NYPL color set from marketing... can i get an ugh?';
ugh

2016-12-20 19:34 UTC, ricardoom reviewed
@mgiraldo updated the partial(s) as per your recommendations. take a look and let me know what your thoughts are.

2016-12-20 20:04 UTC, EdwinGuzman commented on toolkit/sass/_buttons.scss
> +    background-color: $button-border-color;
This mixin doesn't need to have the hover colors inverted like the `squaredButton` mixin? This one also doesn't have the `&:focus` rule.

2016-12-20 20:04 UTC, EdwinGuzman commented on toolkit/sass/_buttons.scss
> +%button-default {
What's the `%` used for here? Where is this being used?

2016-12-20 20:16 UTC, mgiraldo commented
`rounded-button` and `basic-button` should be one and the same (probably `basic-button`. i will merge this PR and make the changes to better illustrate the idea. i also created a [new repo](https://github.com/NYPL/design-toolkit) for the final toolkit that won't include any unrelated assets

2016-12-20 20:18 UTC, merged

2016-12-20 20:20 UTC, ricardoom commented on toolkit/sass/_buttons.scss
> +    background-color: $button-border-color;
@EdwinGuzman i gave it hover state & invertedness b/c I always thought it should have it...
re: :focus, the default button mixin _does_ have the focus and should be applying it to that element... can you run locally and confirm?

2016-12-20 20:23 UTC, EdwinGuzman commented on toolkit/sass/_buttons.scss
> +    background-color: $button-border-color;
Yes, there is a hover state for both buttons.